[package]
name = "state-res"
version = "0.1.0"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
itertools = "0.9.0"
js_int = "0.1.8"
petgraph = "0.5.1"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
tracing = "0.1.16"
maplit = "1.0.2"

[dependencies.ruma]
# git = "https://github.com/ruma/ruma"
path = "../__forks__/ruma/ruma"
features = ["client-api", "federation-api", "appservice-api"]

[dev-dependencies]
lazy_static = "1.4.0"
