[package]
name = "state-res"
version = "0.1.0"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
edition = "2018"
categories = ["api-bindings", "web-programming"]
description = "An abstraction for Matrix state resolution."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "state resolution", "ruma"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ruma/state-res"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
itertools = "0.9.0"
js_int = "0.1.8"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
tracing = "0.1.16"
maplit = "1.0.2"
thiserror = "1.0.20"
tracing-subscriber = "0.2.8"

[dependencies.ruma]
git = "https://github.com/ruma/ruma"
rev = "d5d2d1d893fa12d27960e4c58d6c09b215d06e95"
features = ["client-api", "federation-api", "appservice-api"]

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "state_res_bench"
harness = false