msrv = "1.53"
avoid-breaking-exported-api = false
disallowed-types = []
enforced-import-renames = [ { path = "serde_json::Value", rename = "JsonValue" } ]
standard-macro-braces = [
    { name = "btreeset", brace = "[" },
    { name = "btreemap", brace = "{" },
    { name = "hashset", brace = "[" },
    { name = "hashmap", brace = "{" },
]
