[package]
name = "ruma-state-res"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
categories = ["api-bindings", "web-programming"]
keywords = ["matrix", "chat", "state resolution", "ruma"]
description = "An abstraction for Matrix state resolution."
homepage = "https://www.ruma.io/"
repository = "https://github.com/ruma/ruma"
readme = "README.md"
license = "MIT"
version = "0.1.0"
edition = "2018"

[features]
unstable-pre-spec = ["ruma/unstable-pre-spec"]

[dependencies]
itertools = "0.10.0"
ruma = { version = "0.0.3", path = "../ruma", features = ["events", "signatures"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
maplit = "1.0.2"
thiserror = "1.0.22"
log = "0.4.11"

[dev-dependencies]
criterion = "0.3.3"
rand = "0.7.3"
tracing-subscriber = "0.2.15"

[[bench]]
name = "state_res_bench"
harness = false
