name: Documentation

on:
  push:
    branches: [next]

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install nightly rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Needed for use of unstable options
          toolchain: nightly
          override: true
      - name: Build docs
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options --cfg docsrs"
        with:
          command: doc
          args: --no-deps --workspace --exclude ruma-api-macros --exclude ruma-events-macros --exclude ruma-identifiers-macros --exclude ruma-identifiers-validation --exclude xtask --all-features -Zrustdoc-map
      - name: Deploy to docs branch
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: docs
          folder: target/doc
